### ISSUE TITLE
Sometimes, the USB drive mountpoints is an empty array

### ISSUE THREAD

**Issue by bityogi** [resin-io-modules/drivelist#292] opened 2018-07-25 13:09 UTC
This happens only with some USB drives and not all. 

The USB drive returns an empty array for the **mountpoints** property.

`{
"enumerator":"lsblk:json",
"busType":"USB",
"busVersion":null,
"device":"/dev/sda",
"raw":"/dev/sda",
"description":"Temp SanDisk Ultra USB3.0",
"error":null,
"size":15376318464,
"blockSize":512,
"logicalBlockSize":512,
**"mountpoints":[],**
"isReadOnly":false,
"isSystem":false,
"isVirtual":false,
"isRemovable":true,
"isCard":null,
"isSCSI":false,
"isUSB":true,
"isUAS":null
}`

Earlier when this issue showed up we started using `yarn install` and it went away. But now even with the upgrade to the latest version and using `yarn`, the problem persists.

**Comment by bityogi** [comment] 2018-07-25 13:54
It has worked before with the same drives.

Here is the result from `lsblk --json --all`:

`{
  "blockdevices": [
     {"name": "loop1", "maj:min": "7:1", "rm": "0", "size": "78.9M", "ro": "1", "type": "loop", "mountpoint": "/snap/vscode/38"},
     {"name": "loop8", "maj:min": "7:8", "rm": "0", "size": null, "ro": "0", "type": "loop", "mountpoint": null},
     {"name": "loop6", "maj:min": "7:6", "rm": "0", "size": "143.9M", "ro": "1", "type": "loop", "mountpoint": "/snap/slack/7"},
     {"name": "loop4", "maj:min": "7:4", "rm": "0", "size": "79.4M", "ro": "1", "type": "loop", "mountpoint": "/snap/vscode/42"},
     {"name": "loop2", "maj:min": "7:2", "rm": "0", "size": "86.9M", "ro": "1", "type": "loop", "mountpoint": "/snap/core/4917"},
     {"name": "loop0", "maj:min": "7:0", "rm": "0", "size": "86.9M", "ro": "1", "type": "loop", "mountpoint": "/snap/core/4830"},
     {"name": "sda", "maj:min": "8:0", "rm": "1", "size": "14.3G", "ro": "0", "type": "disk", "mountpoint": "/media/jwentz/Temp"},
     {"name": "loop7", "maj:min": "7:7", "rm": "0", "size": "86.6M", "ro": "1", "type": "loop", "mountpoint": "/snap/core/4650"},
     {"name": "nvme0n1", "maj:min": "259:0", "rm": "0", "size": "477G", "ro": "0", "type": "disk", "mountpoint": null,
        "children": [
           {"name": "nvme0n1p3", "maj:min": "259:3", "rm": "0", "size": "15.8G", "ro": "0", "type": "part", "mountpoint": "[SWAP]"},
           {"name": "nvme0n1p1", "maj:min": "259:1", "rm": "0", "size": "512M", "ro": "0", "type": "part", "mountpoint": "/boot/efi"},
           {"name": "nvme0n1p2", "maj:min": "259:2", "rm": "0", "size": "460.7G", "ro": "0", "type": "part", "mountpoint": "/"}
        ]
     },
     {"name": "loop5", "maj:min": "7:5", "rm": "0", "size": "93.5M", "ro": "1", "type": "loop", "mountpoint": "/snap/slack/6"},
     {"name": "loop3", "maj:min": "7:3", "rm": "0", "size": "78.6M", "ro": "1", "type": "loop", "mountpoint": "/snap/vscode/37"}
  ]
}`

------

Also, here is the result from `df -h --output=source,target`:

`udev           /dev
tmpfs          /run
/dev/nvme0n1p2 /
tmpfs          /dev/shm
tmpfs          /run/lock
tmpfs          /sys/fs/cgroup
/dev/loop3     /snap/vscode/37
/dev/loop5     /snap/slack/6
/dev/loop1     /snap/vscode/38
/dev/loop0     /snap/core/4830
/dev/loop4     /snap/vscode/42
/dev/loop6     /snap/slack/7
/dev/loop2     /snap/core/4917
/dev/loop7     /snap/core/4650
/dev/nvme0n1p1 /boot/efi
tmpfs          /run/user/1001
/dev/sda       /media/jwentz/Temp`

The drive is recognized properly with the mountpoint by both these commands.

**Comment by bityogi** [comment] 2018-07-25 18:12
I have a bit more information to share on this:

In the above `lsblk --json --all` output, the USB drive has the mountpoint defined on the same object:

`{"name": "sda", "maj:min": "8:0", "rm": "1", "size": "14.3G", "ro": "0", "type": "disk", "mountpoint": "/media/jwentz/Temp"}`

Which does not work:

However with another USB, the mountpoint is defined in the children:

`{"name": "sdc", "maj:min": "8:32", "rm": "1", "size": "59.2G", "ro": "0", "type": "disk", "mountpoint": null,
         "children": [
            {"name": "sdc1", "maj:min": "8:33", "rm": "1", "size": "59.2G", "ro": "0", "type": "part", "mountpoint": "/media/kgrover/USB2"}
         ]
      }
`
which does seem to work.

**Comment by jhermsmeier** [comment] 2018-07-25 19:12
Thanks @bityogi! I'll have a look at this a little later today, but my suspicion is that we're not handling the mountpoint on the disk object properly

**Comment by jhermsmeier** [comment] 2018-07-25 23:13
@bityogi this should be patched in https://github.com/resin-io-modules/drivelist/pull/293 now, in case you want to give that branch a run

**Comment by bityogi** [comment] 2018-07-30 13:01
@jhermsmeier , I wanted to confirm that I tested the `fix-no-child-mount-linux` branch. 

And it works beautifully. 

Thanks for the quick follow-up on this and for creating such an awesome library!

**Comment by jhermsmeier** [comment] 2018-07-30 16:14
@bityogi glad to hear that & thank you for the kind words! I'll let you know once it's merged & published (which should happen very soon)!

**Comment by jhermsmeier** [comment] 2018-08-01 18:15
Reopening, as we'll only consider this closed once the PR is merged, and the patch published on npm

**Comment by jhermsmeier** [comment] 2018-08-02 12:56
Oops, sorry for the confusion; reopened the wrong issue here

**Closed by jhermsmeier** 2018-08-02 12:56 UTC
Labels: bug, os:linux

**Comment by ericroy** [comment] 2019-02-20 00:41
I think there may have been a regression here.  We're using v7.0.1 on Centos7, with a usb key that has the mountpoint listed on the primary entry (TYPE=disk), and no child entries (TYPE=part).

The lsblk on Centos7 doesn't seem to support the --json argument, so this is using the pairs parser.

Here's some real output from that system.  We're interested in the mount point of sdc:

```
NAME="sda" MAJ:MIN="8:0" RM="0" SIZE="240065183744" RO="0" TYPE="disk" MOUNTPOINT=""
NAME="sda1" MAJ:MIN="8:1" RM="0" SIZE="209715200" RO="0" TYPE="part" MOUNTPOINT="/boot/efi"
NAME="sda2" MAJ:MIN="8:2" RM="0" SIZE="1073741824" RO="0" TYPE="part" MOUNTPOINT="/boot"
NAME="sda3" MAJ:MIN="8:3" RM="0" SIZE="115835142144" RO="0" TYPE="part" MOUNTPOINT=""
NAME="centos-root" MAJ:MIN="253:0" RM="0" SIZE="53687091200" RO="0" TYPE="lvm" MOUNTPOINT="/"
NAME="centos-swap" MAJ:MIN="253:1" RM="0" SIZE="8455716864" RO="0" TYPE="lvm" MOUNTPOINT="[SWAP]"
NAME="centos-home" MAJ:MIN="253:2" RM="0" SIZE="53687091200" RO="0" TYPE="lvm" MOUNTPOINT="/home"
NAME="sdb" MAJ:MIN="8:16" RM="1" SIZE="" RO="0" TYPE="disk" MOUNTPOINT=""
NAME="sdc" MAJ:MIN="8:32" RM="1" SIZE="31457280000" RO="0" TYPE="disk" MOUNTPOINT="/run/media/DA2E4172/MK-BUILD"
```

Drivelist returns no mount points for sdc, and glancing quickly at the source code, it seems that it only considers the TYPE=part entries when building the mount points list.

https://github.com/balena-io-modules/drivelist/blob/v7.0.1/lib/lsblk/pairs.js#L85

**Comment by lurch** [comment] 2019-02-20 10:54
@ericroy Yeah good catch, seems like #293 only fixed this for the "lsblk json" parser and not for the "lsblk pairs" parser.
@thundron @zvin Looks like this should be re-opened.

**Comment by zvin** [comment] 2019-02-20 15:42
@ericroy @lurch #325 should fix this.

**Comment by ericroy** [comment] 2019-02-20 16:05
Fantastic, thanks for the quick-fix!
