### ISSUE TITLE
ENOENT error on windows

### ISSUE THREAD

**Issue by AndreevskiAleksandar** [resin-io-modules/drivelist#128] opened 2016-12-04 23:04 UTC
Hi,
I tried using the drivelist.list function and it returned this error:
`Error: spawn \scripts\win32.bat ENOENT`

Not really sure is this a problem on my end or something is buggy with the the library.

**Comment by jviotti** [comment] 2016-12-05 03:22
That is very weird. What Windows version are you using? What happens if you run https://github.com/resin-io-modules/drivelist/blob/master/scripts/win32.bat directly? Can you confirm that there wasn't any NPM issues that could caused the downloaded package to lack certain files? What are the contents of the `drivelist` directory inside your `node_modules`?

**Comment by AndreevskiAleksandar** [comment] 2016-12-05 20:48
I am using windows 8.1 64bit.
I just ran the script from a command line and it works fine.

`device: "\\\\.\\PHYSICALDRIVE1"
description: "Generic- Multi-Card USB Device"
size:
raw: "\\\\.\\PHYSICALDRIVE1"
system: False
protected: False
mountpoints: []

device: "\\\\.\\PHYSICALDRIVE0"
description: "WDC WD6400BPVT-75HXZT1"
size: 640132416000
raw: "\\\\.\\PHYSICALDRIVE0"
system: True
protected: False
mountpoints:
  - path: "C:"
  - path: "D:"
  - path: "E:"
`

The contents of the `drivelist` directory: [http://prnt.sc/dfrnfd](http://prnt.sc/dfrnfd)

This is strange... I dont know what could cause this error, since the script itself runs fine on the pc.
I am using your script as a part of a electronJS project, I dont know if that is of any importance though..

**Comment by jviotti** [comment] 2016-12-05 21:05
That is very weird indeed. This module has been developed for an Electron application (https://github.com/resin-io/etcher) so I don't think that is the issue. Can I run this somewhere? Also, what version of Electron is your application running?

**Comment by AndreevskiAleksandar** [comment] 2016-12-05 21:11
I dont have the app up yet, I have started working on it like a week ago. 
But, I do use this template: https://github.com/chentsulin/electron-react-boilerplate. 
You can try on this one. The only thing I have different from this one is a few more react dependencies like modals, tree-ui and so on.. Everything else is the same (I am new to electron so I have yet managed to mess around with it) 
Electron version from the package.json: `"electron": "^1.4.4",`

**Comment by jviotti** [comment] 2016-12-06 01:50
How are you loading/executing `drivelist` in that boilerplate? Maybe you can share a small patch I can apply to the boilerplate to get a setup similar to yours?

**Comment by AndreevskiAleksandar** [comment] 2016-12-06 22:05
Sorry I take so long to respond, I did have some other matters to finish.

About the code, here is the component I use.
I just execute the `drivelist` in the constructor just to see what the results are.. Then I ll find an appropriate usage for it.

```
import React, {Component} from 'react';
import Modal from 'react-modal';
import drivelist from 'drivelist';
import fs from 'fs';

export default class FileDialog extends Component {

  constructor() {
    super();
    this.state = {modalIsOpen: false};
    drivelist.list((error, drives) => {
      if (error) {
        throw error;
      }

      drives.forEach((drive) => {
        console.log(drive);
      });
    });
  }

  openModal = () => {
    this.setState({modalIsOpen: true});
  };

  afterOpenModal = () => {
    // references are now sync'd and can be accessed.
    // this.refs.subtitle.style.color = '#f00';
  };

  closeModal = () => {
    this.setState({modalIsOpen: false});
  };

  render() {
    return (
      <div>
        <button onClick={this.openModal}>Open Modal</button>
        <Modal
          isOpen={this.state.modalIsOpen}
          onAfterOpen={this.afterOpenModal}
          onRequestClose={this.closeModal}
          contentLabel="Example Modal"
        >
        </Modal>
      </div>
    );
  }
};
```

and I also have the `drivelist` in the package.json dependencies (added by --save from npm install)

```
  "dependencies": {
    "drivelist": "^5.0.4",
....
```

**Comment by SomeoneWeird** [comment] 2017-01-08 14:41
Also experiencing this issue.

**Comment by jviotti** [comment] 2017-01-09 15:15
Hi @SomeoneWeird ,

Thanks for reaching out. Do you have something I can clone and run to try to reproduce myself?

**Comment by floreks** [comment] 2017-01-10 14:07
We have exactly the same issue with running external scripts from within our app. It looks like an issue with path or external dependencies resolving when trying to run this script from electron app. It might be connected to webpack or node configuration but I'm not sure.

We've managed to find a workaround for that issue by copying code and patching the code to look for scripts in our scripts directory but we are still looking for a better solution. We also want to use your `etcher-image-write` module and can't run it because of the same issue with path resolving.

This is our repo: https://github.com/maciaszczykm/ubikube

If you add and try to import and use `drivelist` from app then it will fail on finding the script file.

**Comment by jviotti** [comment] 2017-01-10 15:57
Hi @floreks ,

Thanks a lot for the link to the repo. Let me try it myself, and hopefully and I can reproduce this time.

**Comment by jviotti** [comment] 2017-01-10 16:23
Hi @floreks ,

OK, so I found the issue. When you build your application, the JavaScript gets concatenated, but any other resources from the NPM package (like `drivelist` `scripts/` directory) is omitted in the final results, thus ENOENT is rightfully thrown.

There are two solutions as far as I can see:

- You can modify your build system to not omit these resources. I have never used WebPack, but I guess you can somehow specify certain patterns to be copied to the destination, and use that functionality to bring the `scripts` directory automatically. Alternatively, you can whitelist certain extensions, like `.sh` and `.bat`.

- We could inline the source of the platform scripts inside the JavaScript files in `drivelist` and make the module extract them out to temporary files before executing them, so the whole package would be completely self-contained, however that sounds messy and I'd prefer not to do it unless its really a must.

Its weird that you get errors with `etcher-image-write`, since that module doesn't execute any internal child process. 

Notice that we dynamically require `diskpart` if we're running on Windows (https://github.com/resin-io-modules/etcher-image-write/blob/master/lib/win32.js#L27), so I have the theory that web pack tries to process every single `require()` call, but since `diskpart` is a Windows only dependency, it will not be installed on OS X when doing `npm install`, and therefore WebPack will not find it in `node_modules`.

If that's the case, you can do `npm install -f`, which will force platform specific dependencies to be installed to `node_modules`.

Let me know how that goes!

**Comment by floreks** [comment] 2017-01-10 17:14
Hi @jviotti,

> OK, so I found the issue. When you build your application, the JavaScript gets concatenated, but any other resources from the NPM package (like drivelist scripts/ directory) is omitted in the final results, thus ENOENT is rightfully thrown.

Unfortunately we already knew that :), but were unable to find a solution that would force webpack to load raw files (`raw-loader` did not work correctly). I believe that our `etcher-image-write` issues are also caused by webpack configuration.

The weird thing is that once we copied the code and scripts directly to `scripts` dir on our repo then `drivelist` was able to call them even that they are not picked up by webpack. This path resolving is still very vague to me.

> We could inline the source of the platform scripts inside the JavaScript files in drivelist and make the module extract them out to temporary files before executing them, so the whole package would be completely self-contained, however that sounds messy and I'd prefer not to do it unless its really a must.

I wouldn't do that either just to solve some bundler issues. :) With proper configuration everything should work. Webpack is new to us so I believe that we just don't know how to configure it properly.

> Notice that we dynamically require diskpart if we're running on Windows (https://github.com/resin-io-modules/etcher-image-write/blob/master/lib/win32.js#L27), so I have the theory that web pack tries to process every single require() call, but since diskpart is a Windows only dependency, it will not be installed on OS X when doing npm install, and therefore WebPack will not find it in node_modules.

This is actually not our issue with image writer. It looks like it might be connected to our transpiler or also webpack config. Code crashes with very mysterious error `ctor is not defined` in `through2` library.

Thanks for your help! We might end up ditching webpack after all.

**Comment by jviotti** [comment] 2017-01-10 18:45
> The weird thing is that once we copied the code and scripts directly to scripts dir on our repo then drivelist was able to call them even that they are not picked up by webpack. This path resolving is still very vague to me.

So `drivelist` will attempt to load the scripts from `../scripts` relatively to the script location, so if you compile your app to, for example, `myapp/output/app.min.js`, then `drivelist` will attempt to load them from `myapp/scripts`.

I'm happy to make `drivelist` load the scripts relatively to its own code, so in the above case it will look for them at `myapp/output`. Let me know if this helps and I'll make the necessary changes.

> I wouldn't do that either just to solve some bundler issues. :) With proper configuration everything should work. Webpack is new to us so I believe that we just don't know how to configure it properly.

In the case of a desktop application, concatenation and minification is not highly necessary, and I'd assume the impact on runtime speed is minimal (although I bet you're saving a lot of space by doing so). We don't process the JavaScript files in any way in Etcher for instance.

> This is actually not our issue with image writer. It looks like it might be connected to our transpiler or also webpack config. Code crashes with very mysterious error ctor is not defined in through2 library.

Ah, really weird. My first thought was that `ctor` was a native NodeJS C++ addon and thus WebPack was not handling it correctly neither, but looks that that's not the case neither.

> Thanks for your help! We might end up ditching webpack after all.

Yeah, that might be the way to go :) In case you're interested, we have our own set of cross-platform build scripts for Etcher to deal with some things we found other solutions lacking, like proper native module compilation, etc. We plan to release these as a separate project at some point, but feel free to take a look at https://github.com/resin-io/etcher/tree/master/scripts/build in the mid-time.

**Comment by jviotti** [comment] 2017-01-10 18:45
I'll close this issue since its a Webpack specific problem.

**Closed by jviotti** 2017-01-10 18:45 UTC
