### ISSUE TITLE
device on Linux should be more specific

### ISSUE THREAD

**Issue by squirrelpiles** [resin-io-modules/drivelist#69] opened 2016-04-09 22:57 UTC
currently, module returns something like:
device: /dev/sdf
description: Expansion Desk  
size: 4.6T
mountpoint: /media/dave/Seagate\040Expansion\040Drive,
name: /dev/sdf
system: False

but this is really /dev/sdf3.  

Seems like it should include the device/partition, not just the raw device

**Comment by jviotti** [comment] 2016-04-11 03:17
Hi @squirrelpiles ,

Can you paste the output of `lsblk -d /dev/sdf`?

**Comment by squirrelpiles** [comment] 2016-04-11 03:27
$ lsblk -d /dev/sdf
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sdf    8:80   0   4.6T  0 disk 

note if I do the above for /dev/sdf2:
$ lsblk -d /dev/sdf2
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sdf2   8:82   0   4.6T  0 part /media/dave/Seagate Expansion Drive

**Comment by jviotti** [comment] 2016-04-12 15:09
I'm having trouble reproducing this issue. The module uses the following command to detect the connected devices: `lsblk -d --output NAME`. The result is used to populate the `device` property, which equals `/dev/sdf` in your example. So far so good, no partitions (e.g: `/dev/sdf3`) are listed.

In order to get the description, or the size, the module uses: `lsblk -d $device --output MODEL` and `lsblk -d $device --output SIZE`. Since `$device` is `/dev/sdf`, the command to get the description, for example, is: `lsblk -d /dev/sdf --output MODEL`, but somehow it shows the output of `lsblk -d /dev/sdf3 --output MODEL`, which makes no sense.

Can you paste the output of the following commands?

- `lsblk -d --output NAME`
- `lsblk -d /dev/sdf --output MODEL` 
- `lsblk -d /dev/sdf3 --output MODEL` 
- `lsblk -d /dev/sdf --output SIZE` 
- `lsblk -d /dev/sdf3 --output SIZE`

**Comment by squirrelpiles** [comment] 2016-04-12 16:29
I think this:
        lsblk -f /dev/sda --output NAME,MOUNTPOINT
gives you want you need:

$ lsblk -f /dev/sda --output NAME,MOUNTPOINT
NAME   MOUNTPOINT
sda    
├─sda1 /
├─sda2 
└─sda5 [SWAP]



Here are the commands you asked for:
$ lsblk -d --output NAME
NAME
sda
sdf
sdg
sdh
sdi
sdj
sr0

$ lsblk -d /dev/sdf --output MODEL
MODEL
Expansion Desk  

$ lsblk -d /dev/sdf2 --output MODEL
MODEL


$ lsblk -d /dev/sdf --output SIZE
  SIZE
  4.6T

$ lsblk -d /dev/sdf2 --output SIZE
  SIZE
  4.6T

**Comment by ilyabreev** [comment] 2016-07-15 05:34
Voting up for getting partition list instead of raw devices.

**Comment by richardmtp** [comment] 2016-07-26 05:45
Hi,
   I got a result like this
[ { device: '/dev/sda',
    description: 'Hitachi HDS72102',
    size: 250059350016,
    mountpoint: '/',
    name: '/dev/sda',
    protected: false,
    system: true },
  { device: '/dev/sdb',
    description: 'Cruzer Blade',
    size: 8004304896,
    mountpoint: '**/media/xyz/NEW**',
    name: '/dev/sdb',
    protected: false,
    system: false } ]

But actually the second one Cruzer Blade's mountpoint was '**/media/xyz/NEW VOLUME**' or '**cd /media/xpeditions/NEW\ VOLUME/**'
How can i get full path?
Please help me to find out the issues.
Thank you.

**Comment by jviotti** [comment] 2016-07-26 12:38
Hi @richardmtp ,

Thanks a lot for reporting this issue. Looks like we were not handling mount-points with spaces correctly. This has been fixed in https://github.com/resin-io-modules/drivelist/issues/82. I've just released this fix in v3.2.3. Let me know how that goes!

**Comment by richardmtp** [comment] 2016-07-27 10:18
Hi @jviotti 

I have tried with drivelist@3.2.3, It's working fine
Thanks for your immediate response.

**Comment by jviotti** [comment] 2016-10-31 18:47
Closing this in order to continue discussion at https://github.com/resin-io-modules/drivelist/issues/98

**Closed by jviotti** 2016-10-31 18:47 UTC
