### ISSUE TITLE
Electron + Enigma Virtual Box

### ISSUE THREAD

**Issue by devAxeon** [resin-io-modules/drivelist#159] opened 2017-04-12 15:57 UTC
Hi,

Firstly, thanks for this module ! ;)

I use it in [Electron](https://electron.atom.io/) and it work fine !!
Next, I consolidate my app in a single .exe file for windows with [Enigma Virtual Box](http://enigmaprotector.com/en/aboutvb.html) and I got this javascript error:

> Error: spawn C:\mainDev\Apprim\releases\resources\app\node_modules\drivelist\scripts\win32.bat ENOENT (code ENOENT)
    at exports._errnoException (util.js:1022)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193)
    at onErrorNT (internal/child_process.js:359)
    at _combinedTickCallback (internal/process/next_tick.js:74)
    at process._tickCallback (internal/process/next_tick.js:98)

I don't know how to fix it, I don't even know if it's a problem from drivelist, Enigma, or just incompatibility between them ?

Help would be appreciated to make it works, or just telling me that it is impossible ;)

**Comment by jviotti** [comment] 2017-04-12 16:27
Hey there!

Thanks a lot for reaching out. This is a problem we're facing at Etcher as well. The problem is that this module spawns platform scripts to perform its task (https://github.com/resin-io-modules/drivelist/tree/master/scripts), and those will not be included when you concatenate the JavaScript.

We're currently looking at making this module a Node.js C++ add-on (e.g: re-implementing the drive scanning routines in C++), which will solve the problem, so stay tuned!

For now, you should be able to copy the following files https://github.com/resin-io-modules/drivelist/tree/master/scripts after the concatenation to the place your application expects them (C:\mainDev\Apprim\releases\resources\app\node_modules\drivelist\scripts) before packaging your application.

I hope that helps!

**Comment by devAxeon** [comment] 2017-04-13 08:26
Thank you for your explanation !!
Unfortunately, with this option I lost the advantages of a single .exe app...
For the moment I will use my own version of [diskinfo](https://github.com/BenoitGauthier/diskinfo), but I stay tuned with tour module and I willuse it when the C++ add-on will be functional ;)
In any case, great job for etcher, that's a great project !!

**Comment by lurch** [comment] 2017-04-13 09:26
You might want to have a look at how Etcher works - that'd also distributed as a single .exe (see specifically the portable version), but works with an embedded copy of the drivelist scripts (thanks to the ASAR support in Electron, I believe).

**Comment by jhermsmeier** [comment] 2018-05-08 18:04
@devAxeon the C++ binding on Windows has been in for quite a while now, in case you want to give it another shot. I'll close this issue for now, but feel free to reopen should you run into any issues again.

**Closed by jhermsmeier** 2018-05-08 18:04 UTC
